# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ffb889b17a82e79eb3c43f9740fa92188dd4b4b14b917d06e4ab4e24436791afeebfc2e3c053a0af59aae66fcdaa56cc5eda6d5d2b7ea07cf2d1fb2b5a5763e6
  telegram:
    bot:
      token: 184836208:AAHA7Rqvy7kWNNxmsniUij9O643vn7IqDZU
      username: SepogCotecBot
test:
  secret_key_base: 9532d8e8d217db49359075845bf020bf25fbce650d6f7738da82e6272a6ae613b22f8e5b963acab189ea6656d28428d243ef14759b2f41161c46d992caafec83

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
