development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  telegram:
    bots:
      cotec:
        token: <%= ENV["TELEGRAM_TOKEN"] %>
        username: <%= ENV["TELEGRAM_USERNAME_BOT"] %>
        async: true
        token_api: <%= ENV["TELEGRAM_TOKEN_API"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  telegram:
    bots:
      cotec:
        token: <%= ENV["TELEGRAM_TOKEN"] %>
        username: <%= ENV["TELEGRAM_USERNAME_BOT"] %>
        async: true
        token_api: <%= ENV["TELEGRAM_TOKEN_API"] %>

test:
  secret_key_base: 9532d8e8d217db49359075845bf020bf25fbce650d6f7738da82e6272a6ae613b22f8e5b963acab189ea6656d28428d243ef14759b2f41161c46d992caafec83